<?php

namespace AppBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 * seguir con master branch
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
