<?php

namespace AppBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * aca arregle el bug desde la rama hotfix
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
