<?php

namespace AppBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
<<<<<<< HEAD
 * seguir con master branch
=======
 *
 * aca arregle el bug desde la rama hotfix
>>>>>>> hotfix/1.0.0
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
