<?php

namespace AppBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * ProductRepository
 *
 * git 
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{	
	public function paginate($dql, $page = 1, $limit = 3)
	{
	    $paginator = new Paginator($dql);

	    $paginator->getQuery()
	        ->setFirstResult($limit * ($page - 1)) // Offset
	        ->setMaxResults($limit); // Limit

	    return $paginator;
	}

	public function getAllProducts($currentPage = 1, $limit = 3, $order, $idCategory=null)
	{	
		$filterCategory = '';
		if ($idCategory) {
			$filterCategory = 'AND c.id = '.$idCategory;
		}
	    // Create the query
	    $query = $this->createQueryBuilder('p')
	        ->leftJoin('p.category', 'c')
            ->where('c.active = 1 '.$filterCategory)
            ->orderBy('p.'.$order)
	        ->getQuery();


	    $paginator = $this->paginate($query, $currentPage, $limit);

	    return array('paginator' => $paginator, 'query' => $query);
	}
}
